package database

import (
	"github.com/obsidiannnn/Safe-Around/backend/internal/models"
	"gorm.io/gorm"
)

// RunMigrations automigrates all internal structs against the active DB
func RunMigrations(db *gorm.DB) error {
	// 1. Enable required PostgreSQL extensions
	extensions := []string{
		`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`,
		`CREATE EXTENSION IF NOT EXISTS postgis`,
		`CREATE EXTENSION IF NOT EXISTS pg_trgm`,
		`CREATE EXTENSION IF NOT EXISTS btree_gist`,
	}
	for _, ext := range extensions {
		if err := db.Exec(ext).Error; err != nil {
			// Non-fatal: extensions may already exist or require superuser
			_ = err
		}
	}

	// 2. AutoMigrate Go structs → tables
	err := db.AutoMigrate(
		&models.User{},
		&models.Notification{},
		&models.EmergencyContact{},
		&models.UserSession{},
		&models.EmergencyAlert{},
		&models.AlertResponse{},
		&models.AlertEscalation{},
		&models.AlertTimelineEvent{},
		&models.UserLocation{},
		&models.DangerZone{},
		&models.NotificationLog{},
		&models.CrimeIncident{},
	)
	if err != nil {
		return err
	}

	// PostGIS spatial indexes (Emergency Alerts)
	db.Exec(`CREATE INDEX IF NOT EXISTS idx_emergency_alerts_location ON emergency_alerts USING GIST(alert_location);`)
	db.Exec(`CREATE INDEX IF NOT EXISTS idx_emergency_alerts_status ON emergency_alerts(alert_status) WHERE alert_status IN ('active', 'responding');`)
	db.Exec(`CREATE INDEX IF NOT EXISTS idx_alert_responses_alert ON alert_responses(alert_id, response_status);`)

	// PostGIS spatial indexes (Geofencing)
	db.Exec(`CREATE INDEX IF NOT EXISTS idx_user_locations_user_time ON user_locations(user_id, recorded_at DESC);`)
	db.Exec(`CREATE INDEX IF NOT EXISTS idx_user_locations_location ON user_locations USING GIST(location);`)
	db.Exec(`CREATE INDEX IF NOT EXISTS idx_user_locations_recent ON user_locations(recorded_at) WHERE recorded_at > NOW() - INTERVAL '24 hours';`)
	db.Exec(`CREATE INDEX IF NOT EXISTS idx_danger_zones_boundary ON danger_zones USING GIST(boundary);`)
	db.Exec(`CREATE INDEX IF NOT EXISTS idx_danger_zones_risk ON danger_zones(risk_level) WHERE valid_until > NOW();`)
	
	// Create partitioned structure for user_locations using native Postgres inheritance (Mock)
	// Example Partition creation logic can be handled via standalone crons. 
	// The table `user_locations` functions cleanly for development as generated by GORM.

	// Materialized Views (Heatmap)
	db.Exec(`
		CREATE MATERIALIZED VIEW IF NOT EXISTS mv_heatmap_grid AS
		SELECT
			FLOOR(ST_X(location::geometry) / 0.01) as grid_x,
			FLOOR(ST_Y(location::geometry) / 0.01) as grid_y,
			COUNT(*) as incident_count,
			SUM(severity) as severity_total,
			AVG(severity)::float as avg_severity,
			MAX(occurred_at) as last_incident
		FROM crime_incidents
		WHERE occurred_at > NOW() - INTERVAL '30 days'
		  AND verified = true
		GROUP BY grid_x, grid_y;
	`)
	db.Exec(`CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_heatmap_grid ON mv_heatmap_grid(grid_x, grid_y);`)

	return nil
}
